### ISSUE TITLE
All I got are N/A's

### ISSUE THREAD

**Issue by zxzhijia** [boonep/yahoo-finance-scraper#1]
Thanks for sharing. But I ran your code. All it prints are N/A. Also, it reports an error.

[['Ticker', 'Trailing P/E', 'Forward P/E', 'Revenue (ttm)', 'EBITDA (ttm)', 'Total Cash (mrq)', 'Total Debt (mrq)', 'Forward Annual Dividend Yield', 'Payout Ratio', '52-Week Change', 'Short % of Float '], ['CSCO', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['INTC', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['MAT', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['T', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['AAPL', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['TGT', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['STX', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['SO', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A'], ['WMT', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A']]
Traceback (most recent call last):

  File "<ipython-input-2-2b40f6c3b8bf>", line 1, in <module>
    runfile('C:/Users/Xu Zhang/Desktop/MyML_InvestingCode/Getdata.py', wdir='C:/Users/Xu Zhang/Desktop/MyML_InvestingCode')

  File "C:\Users\Xu Zhang\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Xu Zhang\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Xu Zhang/Desktop/MyML_InvestingCode/Getdata.py", line 59, in <module>
    writer.writerows(resultTable)

ValueError: I/O operation on closed file.

**Comment by boonep** [comment]
Hey @zxzhijia, Thanks for reaching out!  Have you done much scraping before?  The code is three years old, some I'm sure yahoo has changed their DOM structure.  This should give you a good basis to update, but I'm a little booked up right now to be updating myself.  If you do update, feel free to open a pull request, so I can share the changes.  Good luck!

**Comment by zxzhijia** [comment]
@boonep I see. No, I haven't done any scraping before. Do you mind to recommend a tutorial or something that I can learn from?

**Comment by boonep** [comment]
@zxzhijia No problem. Once you have your head wrapped around it, it's pretty straight forward and very useful.  http://python-guide-pt-br.readthedocs.io/en/latest/scenarios/scrape/ looks to be a pretty good guide.

I imagine the only thing you'll need to change is line 38: https://github.com/boonep/yahoo-finance-scraper/blob/master/yahoo-finance-scrape.py#L38

**Comment by zxzhijia** [comment]
@boonep I see. Thank you for your help. I'll try that.
